//
// Created by 310165137 on 17/06/2023.
//

#ifndef MULTITHREADED_PSEUDORANDGENERATOR_PREDICTOR_H
#define MULTITHREADED_PSEUDORANDGENERATOR_PREDICTOR_H

#endif //MULTITHREADED_PSEUDORANDGENERATOR_PREDICTOR_H
